export enum ProviderKeys {
  STACKS_NETWORK = 'STACKS_NETWORK',
  STACKS_WALLET_SIGNER = 'STACKS_WALLET_SIGNER',

  SUI_CLIENT_MAINNET = 'SUI_CLIENT_MAINNET',
  ALL_POOLS_PROVIDERS = 'ALL_POOLS_PROVIDERS',
}
