export const ENV = {
  AXELAR_AMPLIFIER_API: import.meta.env.VITE_AXELAR_AMPLIFIER_API,

  BITCOIN_API: import.meta.env.VITE_BITCOIN_API,

  STACKS_API: import.meta.env.VITE_STACKS_API,
  STACKS_SBTC_CONTRACT_DEPLOYER: import.meta.env.VITE_STACKS_SBTC_CONTRACT_DEPLOYER,
  STACKS_SBTC_TOKEN_MANAGER: import.meta.env.VITE_STACKS_SBTC_TOKEN_MANAGER,
  STACKS_AXELAR_CONTRACT_DEPLOYER: import.meta.env.VITE_STACKS_AXELAR_CONTRACT_DEPLOYER,

  ITS_SBTC_TOKEN_ID: import.meta.env.VITE_ITS_SBTC_TOKEN_ID,

  SUI_SBTC_COIN_TYPE: import.meta.env.VITE_SUI_SBTC_COIN_TYPE,
  SUI_CLIENT_URL: import.meta.env.VITE_SUI_CLIENT_URL,

  MICROSERVICE_URL: import.meta.env.VITE_MICROSERVICE_URL,

  STABLE_SWAP_PACKAGE_ID: import.meta.env.VITE_STABLE_SWAP_PACKAGE_ID,
  STABLE_SWAP_POOL_OBJECT: import.meta.env.VITE_STABLE_SWAP_POOL_OBJECT,
};
